### ISSUE TITLE
Documentation in Markdown?

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#100]
Hi @Skiars,
The Berry documentation is very high quality, but is starting to be outdated with the latest additions. Latex is too complex for many users (including me) to edit and update.
Would you consider moving the documentation to Markdown in Github to make Pull Requests and contribution easier?

**Comment by skiars** [comment]
I support this idea. But the migration of documents is a lot of work, and I don't have much time now.

**Comment by diazvictor** [comment]
> I support this idea. But the migration of documents is a lot of work, and I don't have much time now.

I am willing to collaborate with the markdown migration, if desired

**Comment by skiars** [comment]
> > I support this idea. But the migration of documents is a lot of work, and I don't have much time now.
> 
> I am willing to collaborate with the markdown migration, if desired

Great!

**Comment by s-hadinger** [comment]
@Skiars Would you be kind enough to open the wiki feature to all users so we can edit the documentation here?

**Comment by skiars** [comment]
The wiki is already open.

**Comment by s-hadinger** [comment]
Oh yes sorry

**Comment by s-hadinger** [comment]
I did a first pass on the Reference Manual with pandoc and some manual editing. There are still some glitches but it’s mostly usable. 

https://github.com/Skiars/berry/wiki/Reference

**Comment by skiars** [comment]
I took a look at the documentation, and I think it is really usable.
