### ISSUE TITLE
Can't instanciate object if class is a member

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#103]
Sorry, I found a new issue. If a class is returned as a member of an object, I can't instanciate a new object from this class without moving the class to a global or local variable.

```
> m = module()
> class C end
> m.C = C

> m.C()
<class: C>   # wrong, should be <instance: C()>

> C1 = m.C
> C1()
<instance: C()>   #correct
```

**Comment by skiars** [comment]
Ok. I will look at it later.
