### ISSUE TITLE
will you add a plan for driver?

### ISSUE THREAD

**Issue by Soga238** [berry-lang/berry#12]
Will the network stack, file system and other hardware drivers be integrated later? This is what I care about.

**Comment by skiars** [comment]
I have this plan, the next step will support file operations.

But I don't have the energy to integrate a lot of hardware platforms myself.

**Comment by skiars** [comment]
Now Berry already has a file system interface. The interpreter is cross-platform and you can compile directly on your target system.

Hardware drivers are usually easier to make, just make the driver interface into a Berry native function.
