### ISSUE TITLE
Example of calling a berry function from the host ( C api ) 

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [berry-lang/berry#122]
Is it possible to call a berry function from C and if so , could you share an example ?

**Comment by skiars** [comment]
Use `be_call`. If you search for `be_call` in the Berry source code, you should be able to find something you can refer to. For the documentation of C interface, please refer to here: https://github.com/Skiars/berry/wiki/Chapter-8

I suggest you read the code in the [default](https://github.com/Skiars/berry/tree/master/default) folder and [berry.h](https://github.com/Skiars/berry/blob/master/src/berry.h).

The following resources are also available for reference:
- https://github.com/Skiars/berry_regex
- https://github.com/Skiars/berry/blob/master/src/be_mathlib.c
- https://github.com/Skiars/berry/blob/master/src/be_timelib.c

**Comment by JettMonstersGoBoom** [comment]
Thanks . incase anyone is interested. 
```
// load the script
int res = be_loadmode(vm,"main.be",false);
handle_result(vm, res); // from berry.c 
res=be_pcall(vm,0); // this was the line I was missing 
```
then to call a function
```
   res=be_loadstring(vm, "functionFromMain(1)"); // Compile test code
   handle_result(vm, res);
   res=be_pcall(vm,0);
   handle_result(vm, res);
```
