### ISSUE TITLE
string.format() not escaping %%

### ISSUE THREAD

**Issue by Beormund** [berry-lang/berry#124]
string.format("%d%%", 100) should output '100%', but gives runtime_error: bad argument # 3 to 'format': no value.

**Comment by s-hadinger** [comment]
Looking at the source, it seems that '%%' is missing in https://github.com/Skiars/berry/blob/ea5ce5fbb9d1ccf14b5921c35a0dd570e8e8b0f3/src/be_strlib.c#L497
