### ISSUE TITLE
`unimplemented: Thumb-1 hard-float VFP ABI`

### ISSUE THREAD

**Issue by paulrouget** [berry-lang/berry#159]
I'm target a Nordic nRF52 Cortex M4, and I'm compiling with gcc:

`arm-none-eabi-gcc -O3 -g3 -mthumb -mabi=aapcs -Wall -Werror -mfloat-abi=hard -mfpu=fpv4-sp-d16 -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-builtin -fshort-enums`

I'm getting:

```
berry/src//be_api.c:59:1: sorry, unimplemented: Thumb-1 hard-float VFP ABI
```

**Comment by s-hadinger** [comment]
It looks like wrong board selection or compiler option for floating point. Did you select `#define BE_USE_SINGLE_FLOAT 1` in `berry_conf.h` to force 32 bits float?

**Comment by paulrouget** [comment]
Thank you.

If I set BE_USE_SINGLE_FLOAT  to 1 it goes further. But ends with:

```
cc5ds5Yv.s:179: Error: selected processor does not support `vmul.f32 s0,s0,s15' in ARM mode
```

**Comment by s-hadinger** [comment]
That's still a wrong compilation option for your board. It looks like it doesn't support hardware multiplications. I can't help you further

**Comment by paulrouget** [comment]
Issue with my build system. It's working now.
