### ISSUE TITLE
Replacing wiki with a proper documentation site

### ISSUE THREAD

**Issue by blakadder** [berry-lang/berry#163]
Is there interest in moving the wiki to GitHub pages with a better theme intended for documenting code such as

https://pmarsceill.github.io/just-the-docs/
https://vsoch.github.io/docsy-jekyll/

**Comment by skiars** [comment]
I will optimize the document when I have time.

**Comment by skiars** [comment]
I created a  [repository](https://github.com/berry-lang/berry-lang.github.io)  and plan to put the documentation in `berry-lang.github.io/docs`.

But I have no experience with just-the-docs and jekyll ☹️

**Comment by blakadder** [comment]
no worries, I can do that

**Comment by hiperiondev** [comment]
Documentation ported to Sphinx. Maybe this issue should be closed
