### ISSUE TITLE
Feature request: assert function 

### ISSUE THREAD

**Issue by MuresanVladMihail** [berry-lang/berry#17]
I was trying to add a new function, assert, in be_baselib.c but soon I came across an impairment and that is: the lack of getting the current line and file from bvm structure.  
From what I understand reading the source code this is not possible. Please advise.

**Comment by skiars** [comment]
The bvm structure is designed to be invisible to external apis, and the berry api interface operates on a virtual stack.

**Comment by skiars** [comment]
Please wait a moment, I will write some tutorials for this.

**Comment by skiars** [comment]
I made some simple instructions, please see this page: [API Example](https://github.com/gztss/berry/wiki/API-Example). If you need any help, please tell me.

**Comment by MuresanVladMihail** [comment]
Thanks for the example but I already figured how to do that :) 
What I was trying to say is this: Right now there's no way of knowing the location where a "bvalue" has been created at (file and line number). I need this information in order to create an "assert" function (on the C side), eg:
```js 
def assert(cond) 
if (!cond)
  push_error(linenumber, filename)
end
end
```
The solution(?) I came with is to have this modified in "be_object.h":
```C
typedef struct {
#if BE_RUNTIME_DEBUG_INFO > 1
    uint16_t linenumber;
    uint16_t endpc;
#else
    int linenumber;
    int endpc;
#endif
} blineinfo;

typedef struct bvalue {
    union bvaldata v;
    int type;
    blineinfo lineinfo;
} bvalue;
```
And basically everytime you create a variable or modify the value of it the information must change accordingly. 

I would also add in structure blineinfo a const char *fname for knowing in which file the action happened.

Let me know what you think about this. I also have to specify that Lua has a way of getting at runtime debug informations about its objects so _Berry_ should as well and this might be the way.

**Comment by skiars** [comment]
I don't provide such an API, but you can do it.

Please refer to "be_debug.c", this file has examples of source code information at runtime.

**Comment by MuresanVladMihail** [comment]
I will, thank you!

**Comment by skiars** [comment]
Calling the C function `be_debug_error` will terminate the program and output a runtime error message, I think it should be what you want.

**Comment by MuresanVladMihail** [comment]
Not quite, it doesn't report correctly the line number if it's called in the global space aka main function but works correctly if I call it into another function.
```js 
def a()
 def init()
 assert(1 > 2) #works fine! 
end 
end 
assert(1 > 2) # does not work fine, the line number is wrong
```

**Comment by skiars** [comment]
You need trace call stack.

**Comment by skiars** [comment]
Do you have any progress?

I think it would be easier to assert the implementation as a C function. Or, we can implement an error function straight throw, this time will naturally display the call information.

**Comment by skiars** [comment]
You can commit the code to your repository and I can provide some advice.

**Comment by MuresanVladMihail** [comment]
I implemented the assert function as a C function in be_baselib.c and using the blineinfo structure added in bvalue but sometimes I don't get the right line number on which the assert function is being called on the _berry_ side. I have to look more into it.

**Comment by skiars** [comment]
You can run this code:
``` ruby
a = 0
print(a + 'str')
```
Then you will get the following runtime error message:
```
test.be:2: error: unsupported operand type(s) for +: 'int' and 'string'
stack traceback:
        test.be:2: in function `main`
        [C]: in ?
```
Is this expected?

**Comment by MuresanVladMihail** [comment]
I get the same output as you. I'll see if I can reuse some error handling logic from operator '+' and apply it to the assert function.

In case you use IRC maybe we can talk on Freenode, ##netcode ?

**Comment by skiars** [comment]
If an error occurs while calling the function, the call stack will be printed, like:
``` ruby
def func(x)
    return x + 'str'
end
print(func(0))
```
error message:
```
test.be:2: error: unsupported operand type(s) for +: 'int' and 'string'
stack traceback:
        test.be:2: in function `func`
        test.be:4: in function `main`
        [C]: in ?
```

**Comment by MuresanVladMihail** [comment]
If functions would take as a parameter in be_baselib.c the parser structure then error checking would be much easier to handle :)

**Comment by skiars** [comment]
If you call the function [`be_debug_error`](https://github.com/gztss/berry/blob/36be542d7721283d0d7221d9af2eee4793810bd7/src/be_debug.c#L175), you will get the debug message.

**Comment by skiars** [comment]
It will be easier, but it is not conducive to the realization of the external parser.

**Comment by MuresanVladMihail** [comment]
be_baselib.c
```C
static int l_assert(bvm *vm)
{
    int pass = be_tobool(vm, 1);

    if (!pass) {
        be_debug_error(vm, BE_EXEC_ERROR, "Assert failed!");
    }
    be_return_nil(vm);
}
```

```js
class Base1
    var b
    def init(a)
        self.b = a * 3
    end
end
class A1 : Base1
    var c
    def init(c)
        self.c = c
        super(self).init(c)
    end
    def func(a, b)
        return 1 + a + b
    end
    def -*(other)
    end
end

assert(1 > 2) # line 20 in editor 

obj = A1(2)
print(obj.func(5, 6))
print("exiting from class.be") 
```
```
Output: 
native error: Assert failed!
	<native>: in native function
	test/class.be:24: in function `main`
	[C]: in ?
```

**Comment by skiars** [comment]
Nice!

**Comment by MuresanVladMihail** [comment]
The line number in editor does not match the one in stack trace

**Comment by skiars** [comment]
Emmm...

**Comment by skiars** [comment]
It seems that if the error is thrown in the native function, there will be problems with the stack information.

**Comment by MuresanVladMihail** [comment]
Yes!

**Comment by skiars** [comment]
I think the function [`tracestack`](https://github.com/gztss/berry/blob/36be542d7721283d0d7221d9af2eee4793810bd7/src/be_debug.c#L141) may have a problem.

**Comment by MuresanVladMihail** [comment]
Isn't it related to https://github.com/gztss/berry/blob/36be542d7721283d0d7221d9af2eee4793810bd7/src/be_debug.c#L107 ?

Or maybe https://github.com/gztss/berry/blob/36be542d7721283d0d7221d9af2eee4793810bd7/src/be_debug.c#L115 ? 
The last one seems a bit odd to me, especially the "it->endpc > pc" condition

Edit 1:
I did a printf and "pc" seems to return garbage value while "endpc" seems to work fine, please confirm. 
```C
printf("%d %d\n", it->endpc, pc);
    while (it >= start && it->endpc > pc) {
        --it;
    }
```

**Comment by gztss** [comment]
check this https://github.com/gztss/berry/blob/36be542d7721283d0d7221d9af2eee4793810bd7/src/be_vm.c#L470

**Comment by skiars** [comment]
Please wait a moment, I will confirm.

**Comment by skiars** [comment]
Please review the new submission and this issue should be resolved.

Since the IP (instruction pointer) is not pushed onto the stack when the native function is called,
There is a problem with the calculation of the PC. This is not a VM bug, but a performance consideration. Now I have written the `patch_native` function to correct the IP value when I need to print debugging information.

https://github.com/gztss/berry/commit/9c193ea9c8a9d08527b682d3a7a91969911f88f2

And I think this line of code is superfluous: 
https://github.com/gztss/berry/blob/9c193ea9c8a9d08527b682d3a7a91969911f88f2/src/be_debug.c#L182

**Comment by MuresanVladMihail** [comment]
Now it works perfectly! Well done! I was looking at IP and PC this whole time, glad you figure it out!

**Comment by MuresanVladMihail** [comment]
Do you have a more in depth explication why IP is not pushed onto the stack when calling the native function (native function == main function,right?)?

**Comment by skiars** [comment]
Native functions are functions implemented in C, such as `print` and `assert`.

Because there is no bytecode when calling a native function, IP is not used and there is no need to push it onto the stack. If the Berry function is called after this, the IP will be pushed onto the stack and restored after this function returns, so there is no problem.

**Comment by MuresanVladMihail** [comment]
I understand! Thanks!

**Comment by skiars** [comment]
If you can, please do further testing.

**Comment by MuresanVladMihail** [comment]
I will!
