### ISSUE TITLE
Whether the rang operation (a..b) should use the left closed and right open interval

### ISSUE THREAD

**Issue by skiars** [berry-lang/berry#180]
Rang is often used to iterate in a list, sometimes written like this:
``` ruby
for i : [0, 1, 2, 3].size() - 1
  # do somthings
end
```

If the interval is closed on the left and open on the right, this will be simplified to:
``` ruby
for i : [0, 1, 2, 3].size()
  # do somthings
end
```

**Comment by s-hadinger** [comment]
I'm not sure to understand, there is no range above. There is already `list.keys()` to iterate on a list by index:

``` ruby
for i : [0, 1, 2, 3].keys()
  print(i)
end
```

**Comment by skiars** [comment]
In this case, this proposal is unnecessary.
