### ISSUE TITLE
v1.1.0 plan

### ISSUE THREAD

**Issue by skiars** [berry-lang/berry#181]
If we complete the following work, we should release an official v1.1.0 version:

- https://github.com/berry-lang/berry/issues/179
-  https://github.com/berry-lang/berry/issues/180
- https://github.com/berry-lang/berry/issues/177

**Comment by s-hadinger** [comment]
I have a couple of changes around solidify that I will submit before 1.1.0.

**Comment by skiars** [comment]
I opened Projects, so this issue is closed.
