### ISSUE TITLE
Converting COMPTR to int is not safe

### ISSUE THREAD

**Issue by skiars** [berry-lang/berry#189]
Refer to https://github.com/berry-lang/berry/pull/153.

@s-hadinger can you give some usage scenarios? Can we prohibit the conversion of COMPTR to int?

**Comment by s-hadinger** [comment]
I believe we can. This was my first attempt to convert everything to `int`. Then I realized that it was better to make `comptr` an first class type. I need to test if it brakes some of my code though.

Can you please hold on for now?

**Comment by s-hadinger** [comment]
It is fine now, I fixed the Tasmota code to not rely on this. I will submit a PR.
