### ISSUE TITLE
Can't compile if `BE_USE_PERF_COUNTERS` set to `0`

### ISSUE THREAD

**Issue by paulrouget** [berry-lang/berry#207]
```
src/be_gc.c:564:82: error: no member named 'counter_gc_kept' in 'struct bvm'
    if (vm->obshook != NULL) (*vm->obshook)(vm, BE_OBS_GC_END, vm->gc.usage, vm->counter_gc_kept, vm->counter_gc_freed);
                                                                             ~~  ^
src/be_gc.c:564:103: error: no member named 'counter_gc_freed' in 'struct bvm'
    if (vm->obshook != NULL) (*vm->obshook)(vm, BE_OBS_GC_END, vm->gc.usage, vm->counter_gc_kept, vm->counter_gc_freed);
                                                                                                  ~~  ^
2 errors generated.
```

**Comment by paulrouget** [comment]
Same goes for `BE_DEBUG_VAR_INFO`.

**Comment by paulrouget** [comment]
Same goes for `BE_DEBUG_VAR_INFO`.

I think the recent introduction to pycoc breaks `berry_conf.h`. Apparently it's improperly scanning the headers. Not taking into account any `#ifndef` blocks and such.

Edit: I'll file an issue for that specific problem.

**Comment by skiars** [comment]
Do we need to support a full C preprocessor?

**Comment by paulrouget** [comment]
This issue (compilation error with BE_USE_PERF_COUNTERS=0) looks unrelated to the preprocessing issue.
Issue for the preprocessing issue: #208

**Comment by s-hadinger** [comment]
I will fix this. It's not linked to pycoc, just a combination of #ifdefs that fell into the cracks.

**Comment by s-hadinger** [comment]
See #209
