### ISSUE TITLE
be_initupvals never returns

### ISSUE THREAD

**Issue by paulrouget** [berry-lang/berry#225]
A shot in the dark as I'm struggling with a strange issue.

Berry vm "stops" in `be_initupvals`, at this line:

https://github.com/berry-lang/berry/blob/ecc8a24b81f8beef269aac34edf9b71f7b130f44/src/be_func.c#L44

Dereferencing blocks.

Only on my MCU.

At this point, I am suspecting a memory issue on my end, but I'm not 100% sure.

Any idea what else could that be?

**Comment by s-hadinger** [comment]
Sorry but I have never seen that issue.

**Comment by paulrouget** [comment]
Disabling a bunch of features seems to do the trick for now. Pretty sure I'm hitting the memory limit of my MCU.

Closing.
