### ISSUE TITLE
Obsolete documentation

### ISSUE THREAD

**Issue by AlixANNERAUD** [berry-lang/berry#261]
Hello,
Your project seems very interesting but it is not easy to get started with it, since your documentation that's supply on the Wiki or on dedicated repo is obsolete and doesn't explain in details what's going on (especially with the 'porting guide' part and the `map_build` tool which seems to have been moved to pycoc).
Can you give me more explanation about these in order to try to port it to the ESP32 and then I could help you to write the proper documentation.

**Comment by s-hadinger** [comment]
There have been some improvements in the last months, but the porting guide should be mostly still up-to-date.
https://github.com/berry-lang/berry/wiki/Appendix-C

Indeed `coc` was replaced with `pycoc` but it does not change the syntax nor the outputs. `Makefile` was updated accordingly.

Are you stuck somewhere?

**Comment by AlixANNERAUD** [comment]
Thank you for your reply.
Well, I copy all of the file into the main directory of my folder's project (I use Platform IO with Arduino framework), and all of the default configuration files. (I disabled in the `berry_conf.h` all of the module in order to test part by part the implementation). But when I try to compile, the compiler give me issues about some header files that are missing (string manipulation related files I think). So, I've tried few things with pycoc to generate the missing header files but I didn't succeed to use it. So, maybe I missunderstood something about pycoc and the problem is elsewhere ?

**Comment by s-hadinger** [comment]
I strongly suggest you start with `#define BE_USE_PRECOMPILED_OBJECT       0` so you don't need the generated headers in the first steps. Once everything works ok, you can then integrate precompiled objects.

**Comment by s-hadinger** [comment]
I updated https://github.com/berry-lang/berry/wiki/Chapter-9 

Indeed it was severely outdated.

**Comment by AlixANNERAUD** [comment]
Thank you for your feedback and the update of the documentation. I tried what you told me and it worked flawlessly.
Do you need help to export this documentation into a more convient way with using Doxygen and Read the doc ?

**Comment by s-hadinger** [comment]
Thanks for your help but I think we'll keep it in wiki format for now

**Comment by s-hadinger** [comment]
Closing since vastly improved
