### ISSUE TITLE
Publishing the VSC tooling on marketplace

### ISSUE THREAD

**Issue by feelfreelinux** [berry-lang/berry#281]
Hi! Thanks a lot for the work on this project - I use it as a scripting engine in my project, and it's doing it's job absolutely wonderfully. 

Currently, the VSC syntax highlighter is not available from the VSC market. Is it okay if I release it?

**Comment by toaster-code** [comment]
+1 to this.

I am trying to understand how to add the plugin to my vscode. @feelfreelinux can you explain how to do it?

**Comment by feelfreelinux** [comment]
> +1 to this.
> 
> I am trying to understand how to add the plugin to my vscode. @feelfreelinux can you explain how to do it?

In order to do this, go to the tools/... folder, build the plugin as .vsix and then in your vscode, execute "Install from VSIX" from the command palatte. This should open a file picker where you can navigate to your built plugin.

**Comment by skiars** [comment]
All code in this project is distributed under the MIT license, so you can use it for almost any purpose.

Also, I would very much welcome this.

**Comment by feelfreelinux** [comment]
Great! In that case, I've packaged and published [the tooling](https://marketplace.visualstudio.com/items?itemName=berry.berry). In the future, I'll try to expand the extension a little bit.
