### ISSUE TITLE
Print stack trace of exception caught with try/except

### ISSUE THREAD

**Issue by alufers** [berry-lang/berry#327]
Hello,
I am writing a HTTP application in berry, and I am wrapping each request handler with an `try/except` block. On failure I respond with the error message to the client.

Unfortunately catching the exception prevents berry from printing the stack trace where it occurred. Would it be possible to print the stack trace from the exception manually from the `catch` clause?

**Comment by s-hadinger** [comment]
Yes, use:

```berry
import debug
debug.traceback()
```

It prints to stdout the stacktrace.

**Comment by alufers** [comment]
Amazing, sorry for the issue
