### ISSUE TITLE
Documentation sync

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#385]
Hi all. Thanks for the effort done on the documentation here: https://berry.readthedocs.io/en/latest/

However I just realized that the latest changes to the wiki were not reflected in the documentation web site. This is bad.

Why do we need to copy from the wiki to the main repo? Couldn't we just use the wiki to convert to readthedocs?

**Comment by diazvictor** [comment]
> Hi all. Thanks for the effort done on the documentation here: https://berry.readthedocs.io/en/latest/
> 
> However I just realized that the latest changes to the wiki were not reflected in the documentation web site. This is bad.
> 
> Why do we need to copy from the wiki to the main repo? Couldn't we just use the wiki to convert to readthedocs?

We can make a link and place it on the web.

I will also make a small update to place tasmota as we discussed at the time.

**Comment by s-hadinger** [comment]
I don't know who owns https://berry.readthedocs.io/en/latest/

It seems to be @hiperiondev but he doesn't respond anymore

**Comment by diazvictor** [comment]
> I don't know who owns https://berry.readthedocs.io/en/latest/
> 
> It seems to be @hiperiondev but he doesn't respond anymore

I thought it came from https://github.com/berry-lang/berry_doc

**Comment by s-hadinger** [comment]
Nope, it doesn't. It comes from https://github.com/hiperiondev/berry which we have no control on.

**Comment by diazvictor** [comment]
> Nope, it doesn't. It comes from https://github.com/hiperiondev/berry which we have no control on.

We don't have any control over it because it was supposed to be implemented here in the organization by a pull request, but due to the low activity at that time it was demotivated.....

I will try to contact him in a couple of hours.

**Comment by s-hadinger** [comment]
Yes please. Because now we are stuck with a documentation outdated and frozen in time; which even worse than before. I understand he is not motivated anymore, and I would be grateful he passes back control to us.

**Comment by s-hadinger** [comment]
@diazvictor Did you managed to contact @hiperiondev ?

**Comment by s-hadinger** [comment]
I finally took control back of https://berry.readthedocs.io/en/latest/ and updated it with the latest additions to the wiki. The source is now https://github.com/berry-lang/berry_doc

There will be more polishing in the coming days
