### ISSUE TITLE
Error messages are sent to stdout instead of stderr

### ISSUE THREAD

**Issue by sean-niemann** [berry-lang/berry#391]
I've observed that all messages are being directed to stdout.

```
print("@")
print(1/0)
```
stdout:
```
@
divzero_error: division by zero
stack traceback:
	string:2: in function main_
```
stderr:
```
```

The stacktrace (and all errors thus far encountered) do not seem to redirect to stderr.

**Comment by s-hadinger** [comment]
Thanks, but keep in mind that Berry is designed for embedded systems where there does not exist any equivalent to `stdout`. Hence we don't make this distinction when printing errors, they follow the same route.

I don't see any value added to add a significant amount of code to support separate printing routes for `stdout` which embedded systems don't have.

Any specific use for it?
