### ISSUE TITLE
Compilation failed : implicit declaration of function ‘strncasecmp’

### ISSUE THREAD

**Issue by jeason1997** [berry-lang/berry#409]
Platform : raspberry pi a+ , Linux raspberrypi 6.6.20+rpt-rpi-v6 #1 Raspbian 1:6.6.20-1+rpt1 (2024-03-07) armv6l GNU/Linux

But when I followed the approach of this : [Fix compilation #408](https://github.com/berry-lang/berry/pull/408) 
add "#include <strings.h>" to "src/be_strlib.c"
it successfully compiled.

**Comment by s-hadinger** [comment]
See https://github.com/berry-lang/berry/pull/408

**Comment by yuppox** [comment]
I ran into this on two machines. Is there a reason to omit `strings.h` normally?

**Comment by s-hadinger** [comment]
I have submitted #412 to avoid dependency on `strings.h`
