### ISSUE TITLE
Using uninitialized variables

### ISSUE THREAD

**Issue by yuppox** [berry-lang/berry#414]
Hi.

Is this expected behavior? If I append an uninitialized variable to print, it shows a random value. If I try to print the variable on its own, it gives me an error:

```
> print("hello")
hello
> print("hello "..x)
hello 9223372036854775807
> print(x)
syntax_error: stdin:1: 'x' undeclared (first use in this function)
```

It seems like the system should throw an error for the appended print, too.

**Comment by s-hadinger** [comment]
Indeed, that's an unwanted side effect.

**Comment by s-hadinger** [comment]
Wow, this fix made me find a hard to find bug in my Matter code. Thanks !

**Comment by s-hadinger** [comment]
Fixed in https://github.com/berry-lang/berry/pull/415 (waiting for merge)
