### ISSUE TITLE
debug function

### ISSUE THREAD

**Issue by frankgp** [berry-lang/berry#46]
Micropython还是其他的类似的。感觉都没有DEBUG的功能。

如果能具备电脑上IDE而目标设备上运行berry，能够在IDE上进行debug，例如下断电，监视变量什么的。

**Comment by skiars** [comment]
我有开发调试器的计划，不过这个功能相对比较复杂，需要做很多准备。

I have plans to develop a debugger, but this feature is more complicated and requires a lot of preparation.

**Comment by frankgp** [comment]
excellent！ 非常期待！现在通过BERRY和LUA来学习自己做一个虚拟机。

不知道BERRY是否可以关闭GC，并且把变量提前布局，这样就可以做到real time的虚拟机了。

**Comment by skiars** [comment]
调试器目前来看还要一些时间。

关闭 GC 的情况我没有考虑过，不知道 MicroPython 可不可以。

**Comment by s-hadinger** [comment]
It seems this will not happen. Re-open the issue if there are news on this
