### ISSUE TITLE
some doubt

### ISSUE THREAD

**Issue by denisdemaisbr** [berry-lang/berry#49]
1- which compilers are supported?
2- works on 64 and 32-bits OS (targets)?
3- bytecode works across big and little endianess?

great job! 
very impressive

**Comment by skiars** [comment]
1. these are the compilers I have tested: MSVC, gcc, clang, ARMCC.
2. yes (no configuration required).
3. yes ([byte-based storage](https://github.com/Skiars/berry/blob/ba25935931d75eeb144613436c115e04a486ebdc/src/be_bytecode.c#L50), for values longer than 1 byte, use bit-shift operations to extract bytes, not addresses).
