### ISSUE TITLE
import/modules not works?

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#51]
**file.be:**
```
def hi()
    print("hi")
end
```

**import:**

```
> import file
> file.hi()
attribute_error: 'nil' value has no method 'hi'
stack traceback:
	stdin:1: in function `main`
```

**Berry:** latest version.
**OS:** macOS Darwin x86_64

**Comment by enty8080** [comment]
@Skiars , @rofl0r , @MuresanVladMihail

**Comment by skiars** [comment]
You need to write the file *"file.be"* like this:

```
def hi()
    print("hi")
end

m = module('my_module')
m.hi = hi
m.text = 'hello world'

return m
```

import:

```
> import file
> file.hi()
```

Berry uses the return value of the module file as the import result (unlike Python).

**Comment by enty8080** [comment]
Thank you!
