### ISSUE TITLE
Question: what does berry.lib do?

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#54]
@Skiars after compiling Berry on Windows 10 I saw file named berry.lib, I delete it and nothing happened. What does this file do?

**Comment by skiars** [comment]
Yes, you can usually delete berry.lib, it has no effect on execution.

However, in order for berry's dll library to use the symbols exported in berry.exe, we need to link berry.lib when compiling the DLL library.

This line of code is used to generate this lib file:

https://github.com/Skiars/berry/blob/4507c8c7b58b71ea1698700a2e921055c6ac8bf2/Makefile#L18

Here, we use the link option "`-Wl, --out-implib`" to generate import library files.

In the [berry_regex](https://github.com/Skiars/berry_regex) project, we use berry.lib like this:

https://github.com/Skiars/berry_regex/blob/master/Makefile

``` Makefile
TARGET       = regex
CPPFLAGS     = -fPIC -shared -std=c++11 -O2
INSTALL_PATH = /usr/local/lib/berry/packages

ifeq ($(OS), Windows_NT) # Windows
    CPPFLAGS += berry.lib # link berry.lib
    TARGET := $(TARGET).dll
else
    TARGET := $(TARGET).so
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S), Darwin)
        CPPFLAGS += -undefined dynamic_lookup
    endif
endif

$(TARGET):
	@ g++ regex.cpp $(CPPFLAGS) -o $(TARGET)
```


For more information, please see http://www.mingw.org/wiki/sampleDLL

**Comment by enty8080** [comment]
Thanks!

**Comment by enty8080** [comment]
Thanks!
