### ISSUE TITLE
Question: What is the super and real data types?

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#58]
@Skiars What is the super and real data types?

**Comment by skiars** [comment]
real is actually a float number (float or double).
super is the base class.

```
> real('1.23') # convert string to number
1.23
> class mylist : list end # mylist inherits from the list class
> super(mylist) # get super class
<class: list>
```

**Comment by skiars** [comment]
Berry types:

- Nil
- Boolean
- Integer Number
- Real Number
- String
- Function
- Class
- Instance
- Module

Use the function `type` to get the type of value:

```
> type(list)
class
> type([])
instance
```
