### ISSUE TITLE
Question about delay

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#59]
Is there any delay function in Berry like python `time.sleep()`?

**Comment by skiars** [comment]
Not implemented yet.

**Comment by enty8080** [comment]
@Skiars maybe I made this function, but it works like this:

```
>>> import time
>>> time.sleep(1) # ok
>>> time.sleep(0.5) # time_t second = be_toreal(vm, 1) // maybe i doing something wrong?
```

if number is int, it works, but if number is float it is not works :(

**Comment by enty8080** [comment]
If user puts nothing to `time.sleep()` then what is into `vm`?

**Comment by skiars** [comment]
`be_toreal` returns a double value:

``` c
breal be_toreal(bvm *vm, int index);
```

Usually time_t is defined like this:

``` c
typedef long time_t;
```

finally:

``` c
time_t second = be_toreal(vm, 1);  // => (long)0.5 == 0
```

**Comment by enty8080** [comment]
This way is not working

```c
double second = be_toreal(vm, 1)
```

This too

```c
float second = be_toreal(vm, 1)
```

And also I tried this way

```c
breal second = be_toreal(vm, 1)
```

**Comment by enty8080** [comment]
I print second after `float second = be_toreal(vm, 1)` and it returned this

```
>>> import time
>>> time.sleep(0.1)
0.100000
```

In code

```c
sleep(second); // sleep(0.100000) = 0?
```

**Comment by enty8080** [comment]
Debug:

```
debug.c:4:8: warning: implicit conversion from 'double' to 'unsigned int' changes
      value from 0.1 to 0 [-Wliteral-conversion]
        sleep(0.100000);
        ~~~~~ ^~~~~~~~
1 warning generated.
```

sleep() does not support `float`, it needs `unsigned int`, that means that my `time.sleep()` cannot work with `float` numbers.

**Comment by enty8080** [comment]
I wrote my own sleep function and it works with float numbers.

**Comment by enty8080** [comment]
@Skiars #60

**Comment by skiars** [comment]
I don't think the delay of using loops is really sleep, it will consume a lot of CPU without suspending thread.

You can use `usleep` in Linux:

``` c
#include <unistd.h>
int usleep (useconds_t usec);

breal sec = 0.1;
usleep((useconds_t)(sec * 1000000)); // seconds to microseconds
```

There is no similar API for Windows.

**Comment by skiars** [comment]
If an API is platform dependent, please consider using *default/be_port.c* and *src/be_sys.h* for compatibility.

**Comment by enty8080** [comment]
**Solution:**

```c
#if defined(_WIN32)
    #include <windows.h>
    #define usleep(x) Sleep((x))
#else 
    #include <unistd.h>
#endif 

static int m_sleep(bvm *vm)
{
    if (vm != NULL) {
        double milisecs = be_toreal(vm, 1);
        #if defined(_WIN32)
            unsigned int secs = milisecs * 1000; // 1
        #else 
            unsigned int secs = milisecs * 1000000; // 2
        #endif 
        usleep(secs);
        be_return_nil(vm);
    } else {
        be_return_nil(vm);
    }
}
```
But if we will use this solution then 0.5 will be translated to 500 miliseconds, but 0.005 will be 0.
**1.** `windows.h` does not has microseconds delay but it has miliseconds delay.
**2.** `unistd.h` does not has miliseconds delay but it has microseconds delay.

**Comment by skiars** [comment]
Yes. I think you can refer to the implementation of CPython.

**Comment by enty8080** [comment]
```
src/be_timelib.c: In function ‘m_sleep’:
src/be_timelib.c:61:9: error: implicit declaration of function ‘usleep’; did you mean ‘sleep’? [-Wimplicit-function-declaration]
   61 |         usleep(secs);
      |         ^~~~~~
      |         sleep
make: *** [Makefile:58: src/be_timelib.o] Error 1
```

Replace `-std=c99` with `-std=gnu99` in Makefile to use unistd.h with usleep

**Comment by enty8080** [comment]
Replace `-std=c99` with `-std=gnu99` in Makefile to use unistd.h with usleep

**Comment by enty8080** [comment]
It works!

**Comment by skiars** [comment]
Don't use gnu99, just use c99.

CPython sleep implementation:

https://github.com/python/cpython/blob/91e1bc18bd467a13bceb62e16fbc435b33381c82/Modules/timemodule.c#L1888

CPython uses `select` function to realize the `sleep` of Unix-like systems.

**Comment by enty8080** [comment]
@Skiars berry is cross-platform, time.sleep() should work in windows too, not only in Unix-like systems.

**Comment by skiars** [comment]
Sorry, I am not complete, the following link actually has sleep implementation under Windows. I just pointed out a sleep implementation that does not depend on gnu99 in Linux.

https://github.com/python/cpython/blob/91e1bc18bd467a13bceb62e16fbc435b33381c82/Modules/timemodule.c#L1888

The implementation in this link is definitely cross-platform 😉.

**Comment by enty8080** [comment]
@Skiars Why we should not use `gnu99` instead of `c99`?

**Comment by skiars** [comment]
GNU99 comes with some GNU extensions, and currently I want to use the ISO C99 standard as much as possible. There is no special reason.

I hope users can ensure that Berry is successfully compiled even when only C99 compiler is available.
