### ISSUE TITLE
try-except does not work.

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#62]
```ruby
try
    undeclaratedvariable
except .. as e, v
    print("error")
end
```

This is not work, it should return `error` but it returns `'undeclaratedvariable' undeclared`. Why?

**Comment by skiars** [comment]
This is a compilation error, try-except can only catch runtime errors (when the compilation has not been completed, we do not know that there is a try-cache block).

The following compilation errors can be catch:

``` ruby
try
    compile('undeclaratedvariable')
except .. as e, v
    print("error")
end
```

At this time the compilation error in `compile` will be catch.

You can see this example (run with berry `berry repl.be`):

https://github.com/Skiars/berry/blob/master/examples/repl.be

And, I am planning to write an English language reference manual.

**Comment by enty8080** [comment]
@Skiars one more question about `do` keyword. What `do` does?
Is there any difference between:
```
do
    print("Hello, world!")
end
```
and just
```
print("Hello, world!")
```
?

**Comment by skiars** [comment]
`do` - `end` only provides a scope level, similar to C or JS's `{ ... }`
