### ISSUE TITLE
Few questions.

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#63]
@Skiars 

**1.** What `__iterator__` does?

**2.** Why `isinstance` does not work?

```
>>> type(a)
instance
>>> isinstance(a)
false
```

**3.** What `classof` does and `issubclass` does?

**4.** Why this happens:

```
>>> n = 0
>>> type(n)
int
>>> type(n) == int
false
```

?

I think it should return `true`, because `n` is `int`.

**I know this is stupid question, but there is no english docs :(**

**Comment by skiars** [comment]
This is a short manual: [short_doc.pdf](https://github.com/Skiars/berry/files/4900425/short_doc.pdf).

I will upload the source code of this document later.

**Comment by enty8080** [comment]
@Skiars Does berry has function `from math import *` to not use `math.pow(5, 2)`, just `pow(5, 2)`?

**Comment by skiars** [comment]
There is currently no such syntax. Now, this is harder to do.

**Comment by enty8080** [comment]
@Skiars,  I have a question about your REPL, when I trying to use tab in it, it does not works and shows me directory contents:

```
> (tab)
.idea    myfiles samples
>> (tab)
.idea    myfiles samples
```

**Comment by skiars** [comment]
Can you elaborate? I don't understand.

**Comment by enty8080** [comment]
@Skiars everything is ok. This is a problem in my OS :)

**Comment by skiars** [comment]
Okay, it looks strange.
