### ISSUE TITLE
async / await support - the function based implementation

### ISSUE THREAD

**Issue by engelant** [berry-lang/berry#66]
I just think the support of `async`/`await` can be divided into two steps:

**1. First implement async/await with library functions;**
2. Implement related syntactic sugar.

We should open a new issue.

_Originally posted by @Skiars in https://github.com/Skiars/berry/issues/65#issuecomment-669629602_

**Comment by skiars** [comment]
Good. Recently I am trying js asynchronous operation, I think this will give some inspiration.
