### ISSUE TITLE
idea: namespace management

### ISSUE THREAD

**Issue by enty8080** [berry-lang/berry#67]
I have an idea about namespace management.

Code:

```
import os
os.system("ls")
```

Code with namespace improvements:

```
import os
system("ls")
```

**Comment by skiars** [comment]
I think this is not good because of scope pollution.

**Comment by enty8080** [comment]
Why not to do something like in python?

```python
from os import *
system("ls")
```

**Comment by skiars** [comment]
I hope to support this syntax. But it is difficult to do this with current VM because of the static scope.
