### ISSUE TITLE
How to iterate on map keys?

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#74]
I didn't find any way to iterate on map keys, `iter()` actually returns a iterator for values, not keys:

```
> m={"a":1,"b":2,"c":3}
> for i: m print(i) end
1
2
3
```

Did I miss something?

**Comment by s-hadinger** [comment]
I think I found the problem, changed `be_maplib.c` line 159:

From

```
    var_setstr(vm->top, &next->value);
```

To

```
    var_setobj(vm->top, next->key.type, next->key.v.p);
```

Now I get:
```
> m={"a":1,"b":2,"c":3} for i: m print(i) end
a
b
c
```

Do you want a PR?

**Comment by skiars** [comment]
I do not intend to allow the default iterator to support (key, value) iteration, because the efficiency may not be good. But we can consider returning a key-value pair iterator through a certain method of `map`. Like:

```
for i : { "a": "b", "c": "d" }.pairs()
    print(i) # ("a", "b"), ("c", "d")
end
```

**Comment by s-hadinger** [comment]
Thanks for your answer. I was only asking for an iterator on keys, not necessarily (key,value) pairs. Or maybe we can add `map.iterkeys()` to have such iterator on keys.

**Comment by skiars** [comment]
Ok. We should be able to use it like this:

```
for i : m.keys()
    print(i, m[i])
end
```

I think this might be faster than `map.pairs()` (this will construct iteration objects many times, but Berry VM has no object cache yet).

**Comment by s-hadinger** [comment]
Agreed :)
