### ISSUE TITLE
Bug in gc counting, false memory leak

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#79]
Hi, I suspected a memory leak, but it appears instead that the RAM does not increase, yet the reported ram usage is wrong.

```
> import gc
> def g() gc.collect() return gc.allocated() end
> g()
2324
> l = []
> for i:0..5000 l.iter() end
> g()
82961
> for i:0..5000 l.iter() end
> g()
163009

> m = {}
> for i:0..5000 m.iter() end
> g()
243355
```

Monitoring the actual ram usage, iterators are correctly garbage collected and deallocated. However the counting in `gc.allocated()` is wrong and falsely increases.

**Comment by s-hadinger** [comment]
Fixed in https://github.com/Skiars/berry/pull/80

**Comment by skiars** [comment]
👏
