### ISSUE TITLE
operator overload fails

### ISSUE THREAD

**Issue by JettMonstersGoBoom** [berry-lang/berry#9]
steps: build berry . 
run berry test\test.be 
note results of operator tests 

reload operator test: A(100) + A(20) = nil
reload operator test: A(100) > A(20) = nil

**Comment by skiars** [comment]
It's maybe a bug, I will deal with it later.

**Comment by skiars** [comment]
I think the problem may be in the function `object_binop()` of the source file "src/be_vm.c".

**Comment by skiars** [comment]
The bug has been fixed. Please check the commit [`71f0d4a`](https://github.com/gztss/berry/commit/71f0d4afe92a1d48c862b8e63c317a1ccba3df3b).

**Comment by JettMonstersGoBoom** [comment]
perfect thanks
