### ISSUE TITLE
Race condition when creating class via `be_regclass`

### ISSUE THREAD

**Issue by s-hadinger** [berry-lang/berry#94]
Hi,
I've been chasing a hard to find crash for 3 evenings, and I now understand the problem.

When calling: `be_regclass()`, it calls `class_auto_make()` then `class_init()`. This is where there is a race condition happens:

```
static void class_init(bvm *vm, bclass *c, const bnfuncinfo *lib)
{
    if (lib) {
        while (lib->name) {
            bstring *s = be_newstr(vm, lib->name);
            if (lib->function) { /* method */
                be_prim_method_bind(vm, c, s, lib->function);
            } else {
                be_member_bind(vm, c, s); /* member */
            }
            ++lib;
        }
        be_map_release(vm, c->members); /* clear space */
    }
}
```

When creating the first attribute of the class, a `bstring` object is allocated for the name of the member. Then it is added via `be_member_bind()`. Until now, `c->members == NULL` which is the root of the problem.

Before adding to the map, it is first resized, which creates a new object. In my case, this triggered a GC.

When doing the GC, the attribute name `bstring` object is not yet attached to `c->members` since the map does not exist. The GC removes the `bstring` object attached to nothing.

Right after, the `cl->members` is created and but the `bstring` object is now freed and corrupt. Eventually it creates a crash.

I can't find any simple solution to mark the `bstring` object temporarily not garbage collectible, and setting GCONST would change its semantics.

Since `be_regclass()` is only created at launch, I used a work-around and disable GC during `be_regclass()`:

```
static void class_init(bvm *vm, bclass *c, const bnfuncinfo *lib)
{
    if (lib) {
        be_gc_setpause(vm, 0);
        while (lib->name) {
            bstring *s = be_newstr(vm, lib->name);
            if (lib->function) { /* method */
                be_prim_method_bind(vm, c, s, lib->function);
            } else {
                be_member_bind(vm, c, s); /* member */
            }
            ++lib;
        }
        be_gc_setpause(vm, 1);
        be_gc_auto(vm);
        be_map_release(vm, c->members); /* clear space */
    }
}
```

Do you have any other idea?

**Comment by skiars** [comment]
This is indeed a bug. To ensure that the GC is safe without stopping the GC, it needs to be handled very carefully.
